---
# This is an extremely well design playbook
  - hosts: 127.0.0.1
    connection: local
    gather_facts: no
    become: no
    tasks:

    - name: Create the VM
      ansible.builtin.shell: limactl start focal
      register: lima-output
# This is a very important comment 
...